universe = vanilla
Executable = condor_executable.sh
Arguments = $(Process)
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = zcfiles.tgz
Output = logs/condor/zcanalyzer_$(Cluster)_$(Process).stdout
Error = logs/condor/zcanalyzer_$(Cluster)_$(Process).stderr
Log = logs/condor/zcanalyzer_$(Cluster)_$(Process).log
notify_user = ${LOGNAME}@FNAL.GOV
+LENGTH="SHORT"
x509userproxy = /tmp/x509up_u42382
Queue 1
