universe = vanilla
Executable = condor_executable.sh
Arguments = $(Process)
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = zcfiles.tgz
Output = log/condor_out/zcanalyzer_$(Cluster)_$(Process).stdout
Error = log/condor_err/zcanalyzer_$(Cluster)_$(Process).stderr
Log = log/condor_log/zcanalyzer_$(Cluster)_$(Process).log
notify_user = ${LOGNAME}@FNAL.GOV
+LENGTH="SHORT"
x509userproxy = /tmp/x509up_u42382
Queue 1
